mode: :thresholds # :fit, :half, :third
thresholds:
- :workers: 1
  :job_count: 1
- :workers: 2
  :job_count: 15
- :workers: 3
  :job_count: 25
- :workers: 4
  :job_count: 40
- :workers: 5
  :job_count: 60
environments:
  - production
  - staging
  - development
worker_name: worker
threshold: 100
